from pydantic import BaseModel, Field
from typing import Optional, Literal
from datetime import timedelta, datetime   # for Interval type

'''
Specify data transfered via net (response/requests) for:
   1. auto validation + corresponding HTTP responses - for specified types and conditions of poles violation 
   2. also gives neat OpenAPI methods` documentation: example value and schema
'''


# ======= Response =======
# API response template
class API_Response(BaseModel):
   class MetaData(BaseModel):
      total:    int = Field(default=0, description='total amount of entities')
      metadata: str = Field(default='metadata here', description='data about data') 
   
   data: list[object]             = Field(default=[], description='actual data from Data base')
   meta: Optional[MetaData]       = Field(default={}, description='data about data (mostly for pagination)') 
   # some request info:
   status: str                    = Field(default='not implemented', description='code-word to identify response from API | why? - 400 code may be caused by several reasons - so status-code-word clarifies the reason of 400-code') 
   details: Optional[str]         = Field(default='', description='details about status | see response_details.py  | for ex explain why client gets 400-code and how to fix it') 
   error_values: Optional[object] = Field(default='', description='exact values that caused an exception')


# ======= /search Request =======
class PaginationParams(BaseModel):
   limit: int           = Field(ge=1, description='Amount of elements on a page')
   page:  int           = Field(ge=1, description='Page number')
   order: Optional[str] = Field(description='(Optional) ordering for displayed page in ASC or DESC (with leading "-") order by column', default=None)

class FilterParams(BaseModel):   
   filter_column: str   = Field(description='Column to search in')
   value: str           = Field(description='Value to search to')
   method: Literal ['ilike', 'like', 'equal'] = Field(description='Method to search')



# ==== Tables (without autogenerated poles - only to fill by hands)

# separate inherit from BaseModel, due there`s different PK (category) - not id and excluding pole is too tricky ( Field(exclude=True) doesn`t work and stackoverflow suggest post-proceessing xD`) 
class WasteCategory(BaseModel):
   category: Literal ['биоотходы', 'стекло', 'пластик'] = Field(description='Category of wastes')
   time_to_recycle: timedelta

class Polluter_OO(BaseModel):
   name: str    = Field(description='Name of polluter organisation')
   x_geo: float = Field(description='Geo coordinate X')
   y_geo: float = Field(description='Geo coordinate Y')

class PolluterWaste(BaseModel):
   amount: int                                          = Field(ge=1, description='Amount of wastes in this waste package')
   category: Literal ['биоотходы', 'стекло', 'пластик'] = Field(description='Category of wastes')
   polluter_id: str                                     = Field(description='Waste owner', length=36)
   

'''
#TODO-Microsevice
   !!! mb will be usefull for HTTP request to Recycler Microservice 
   - or mb not (some poles aren`t needed for Recycler to define if it has free slots for Wastes)
   
   - Was used in IPC to feed data to Demon 
   - much alike to HTTP request where raw sqlalchemy model is invalid to pass
    
'''
def convert_to_pydentic(model_obj, pydentic_cls):
   '''   
   sql_alchemy_model -> pydentic object

      - also converts UUID poles to str (id pole: pole "id" or pole that ends with "_id")
   '''
   params = model_obj.__dict__
   for k, v in params.items():
      # cast ids to str - to make pydentic and postgres CALM about UUID4 and str for id in different places - everywhere`ll be str
      if k == 'id' or k.endswith('_id'):
         params[k] = str(v)         

   return pydentic_cls(**params)

