from fastapi import APIRouter, Depends, Body, HTTPException, Response
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, func

from math import ceil

from app.data.db import get_db_session, sessionFactory
from app.data.orm import Models
from app.data.schemas import *
from app.web.response_statuses import common_statuses
from app.web.status_code_handle import category_handler, unpositive_amount_handler, try_except_commonHandler

from app.web.feature.helpers import prepare_params            # for /search
from app.data.preparing.build_some_tables import Build_Tables # reuse generation records for Tables from mock-function. also we can reuse Factories from mocktables + push in db - like in Build_Tables :)

router = APIRouter(prefix='/polluter')


@router.post('', status_code=201, summary='add polluter-organization')
async def create_polluter(
    name:  str   = Body(description='company name'), 
    x_geo: float = Body(description='X coordinate of company'),
    y_geo: float = Body(description='Y coordinate of company'),
    SessionLocal: AsyncSession = Depends(get_db_session)
):
    polluter = Models.Polluter_OO(name=name, x_geo=x_geo, y_geo=y_geo)
    SessionLocal.add(polluter)
    await SessionLocal.commit()
    await SessionLocal.refresh(polluter)     # just to enshure all autogenerated values are alreay computed in db before we send response
    
    # send_command_to_demon('Polluter_OO_ADD', convert_to_pydentic(polluter, Polluter_OO))
    return API_Response(
        **common_statuses[201]['CREATED'],
        data=[convert_to_pydentic(polluter, Polluter_OO)]
    )

@router.post('/polluter-wastes', status_code=201, summary='Add (register/publish) some waste')
@try_except_commonHandler  # handle FK (id) related execeptions from db - by catching it in decorator`s wrapper
async def add_polluter_wastes(
   polluter_waste: PolluterWaste = Body(),
   SessionLocal: AsyncSession = Depends(get_db_session)
):
    ''' Registrate new waste (of some category and amount) by some polluter organization. contracted partner (recycler/logist) will watch this queue by contract_id '''
    polluter_id, amount, category = polluter_waste.polluter_id, polluter_waste.amount, polluter_waste.category

    # handling invalid params
    if amount < 1: return unpositive_amount_handler(amount) 
    category_handler(category) # Rise HTTP exception 409 if chosen category doesn`t excists
    
    polluter_waste = Models.PolluterWaste(
        polluter_id = polluter_id,
        category    = category,
        amount      = amount
    )

    SessionLocal.add(polluter_waste)
    await SessionLocal.commit()
    await SessionLocal.refresh(polluter_waste)     # just to enshure all autogenerated values are alreay computed in db before we send response

    # send_command_to_demon('PolluterWaste_ADD', convert_to_pydentic(polluter_waste, PolluterWaste))
    return API_Response(
        **common_statuses[201]['CREATED'],
        data=[convert_to_pydentic(polluter_waste, PolluterWaste)]
    )


@router.post('/polluter-wastes/fill/random', status_code=201, summary='Add amount of random wastes from random polluteres')
async def add_polluter_wastes(
    amount: int = Body(description='amount of wastes to add')
):
    '''Generate random wastes (type + amount) by random Polluter'''
    if amount < 1: return unpositive_amount_handler(amount) 
    
    rnd_wastes = await Build_Tables.OO_wastes_populate(amount)  # reuse generation records for Tables from mock-function
        
    return API_Response(
        **common_statuses[201]['CREATED'],
        data=rnd_wastes,
        meta=API_Response.MetaData(total=amount, metadata='mock-generated data')
    )

# use 200 code on success - for verbose deletion output (204 code can`t provide space for content)
@router.delete('/{polluter_id}', status_code=200, summary='delete pollutter')
@try_except_commonHandler
async def del_polluter(
    polluter_id: str
):
    async with sessionFactory() as session:
        row = await session.execute(select(Models.Polluter_OO).where(Models.Polluter_OO.id == polluter_id))
        row = row.scalar_one_or_none()
        name = row.name
        await session.delete(row)
        await session.commit()      # prevent silent rollback() on error 
        # NOTE: cascade deletion of all the Polluter`s child-entities is already configured in models - see "ondelete='CASCADE'" in orm.py        

        return API_Response(
            **common_statuses[200]['DELETED'],
            data=[name]
            )


# TODO: Auth via ~AAA-Microservice - Polluter (must be owner of waste) 
@router.delete('/polluter-wastes/delete/{polluter_waste_id}', status_code=200, summary='manual delete published wastes in case of mistake')
async def release_polluter_waste(
        polluter_waste_id: str
    ):
    ''' Release wastes if contract is performed '''

    async with sessionFactory() as session:
        row = await session.execute(select(Models.PolluterWaste).where(Models.PolluterWaste.id == polluter_waste_id))
        row = row.scalar_one_or_none()
        await session.delete(row)
        await session.commit()      # prevent silent rollback() on error 

        return API_Response(
            **common_statuses[200]['DELETED'],
            data=[f'Manually delted polluter waste: {polluter_waste_id}']
            )

# TODO: somehow handle Contract: 
#   1. Check Contract status before action (body param)
#   2. Verify Contract Provider (via ~AAA-Microservice)
@router.delete('/polluter-wastes/contract/{contract_id}/done', status_code=200, summary='(TODO - contract (provider) handling) | release wastes that was carried by Logist according to Contract.')
async def release_polluter_waste(
        contract_id: str
    ):
    ''' Release wastes if contract is performed '''

    async with sessionFactory() as session:
        rows = await session.execute(select(Models.PolluterWaste).where(Models.PolluterWaste.contract_id == contract_id))
        rows = rows.scalars().all()
        #print(f'contracted rows - {rows}') 
        for row in rows: await session.delete(row)  # not CASCADE, due Contracts Table is on different microservice 
        await session.commit()      # prevent silent rollback() on error 

        return API_Response(
            **common_statuses[200]['DELETED'],
            data=[f'contract-{contract_id} success for Polluter. Relesed {len(rows)} waste positions']
            )
    
# TODO: somehow handle Contract: 
#   1. Verify Contract Provider (mb Pub Key in Body param)
#   2. Check Contract status before action
@router.put('/polluter-wastes/contract/{contract_id}/fail', status_code=200, summary='(TODO - Polluter Auth) | Set contract tag back to NULL due contract failed')
async def resign_contract(
    contract_id: str,     
):
    ''' Handle contract_id failure: when release_time is over - Contract Microservice will pull this endpoint (inform polluter_id) '''    
    async with sessionFactory() as session:    
        rows = await session.execute(select(Models.PolluterWaste).where(Models.PolluterWaste.contract_id == contract_id))
        rows = rows.scalars().all()
        for row in rows: row.contract_id = None
        await session.commit()      # prevent silent rollback() on error 

        return API_Response(
            **common_statuses[200]['OK'],
            data=[f'contract-{contract_id} failure message is delivered to Polluter. Resigned contract for {len(rows)} waste positions']
            )


# TODO: Auth via ~AAA-Microservice - Polluter (must be owner of waste) 
@router.put('/polluter-wastes/update/{polluter_waste_id}', status_code=200, summary='(TODO - Polluter Auth) | Manual update ammount of published waste in case of mistake.')
async def correct_amount(
    polluter_waste_id: str,
    amount: int
):
    async with sessionFactory() as session:
        if amount == 0: return Response(status_code=409, content='to delete resourse - use DELETE method')  # special case
        if amount < 1: return unpositive_amount_handler(amount)

        row = await session.execute(select(Models.PolluterWaste).where(Models.PolluterWaste.id == polluter_waste_id))
        row = row.scalar_one_or_none()
        
        row.amount = amount
        await session.commit()      # prevent silent rollback() on error 

        return API_Response(
            **common_statuses[200]['OK'],
            data=[f'updated amount: {amount}']
            )


# Read all Table`s columns 
async def read_table(
        ORM_Model, 
        Schema: BaseModel):
    '''typical read + convert: db -> sqlalchemy -> pydentic'''
    
    async with sessionFactory() as session:
        rows = await session.execute(select(ORM_Model))
        rows = rows.scalars().all()
        if len(rows) == 0:
            return Response(204)        # special case with no metadata on purose: 204 must have no 'content'

        rows = [Schema(**el.__dict__) for el in rows]    # TODO: find different neet way to fill pydentic models, due uncpacking as dictionary mb dirty    
        return API_Response(
            **common_statuses[200]['OK'],
            data=rows, 
            meta=API_Response.MetaData(
                total=len(rows)
            ))


@router.get('', summary='get all polluter organizations')
async def get_all_polluters():
    return await read_table(Models.Polluter_OO, Polluter_OO)

@router.get('/polluter-wastes', summary='get all the polluters` wastes')
async def get_all_polluter_wastes():
    return await read_table(Models.PolluterWaste, PolluterWaste)

@router.get('/waste-categories', summary='get all excisting waste types')
async def get_all_polluter_wastes():
    return await read_table(Models.WasteCategory, WasteCategory)


# Search: pagination + filtering + sorting
async def search(   
        pagination: PaginationParams, 
        filter: Optional[FilterParams],
        schema,
        model,
        sessionFactory: AsyncSession
    ):
     
    async with sessionFactory() as session:
        stmt = select(model)
        
        # search 
        if filter:
            search, search_col, method = filter.value, filter.filter_column, filter.method  
            if search_col in model.__table__.columns.keys():
                # chose search method for statement
                if method   == 'ilike': # case-insensitive
                    stmt = stmt.filter(model.__dict__[search_col].ilike(f'%{search}%')) # %-wrapping - need for db to search partitial mathing
                elif method == 'like':  # case-sensitive
                    stmt = stmt.filter(model.__dict__[search_col].like(f'%{search}%'))
                elif method == 'equal': # sensitiviest :)))
                    stmt = stmt.where(model.__dict__[search_col] == search)   
            else:
                return Response(status_code=422, content=f'no such column to search in: {search_col}')

        # pagination
        if pagination.order and pagination.order.lstrip('-') not in model.__table__.columns.keys():
            return Response(status_code=422, content=f'no such column to ORDER BY: {pagination.order}') 
        
        skip, order = prepare_params(pagination, model)

        stmt_COUNT = select(func.count()).select_from(stmt) # COUNT by database
        total = await session.execute(stmt_COUNT)
        total = total.scalar()

        if pagination.page > ceil(total / pagination.limit): 
            return Response(status_code=422, content=f'max page number is: {ceil(total / pagination.limit)}, while page #{pagination.page} was requested')
        
        # sorting - must be called before slicing (group by must be before limit amd offset)
        if not order == False:  # NOTE: 
           stmt = stmt.order_by(order)

        # pagination - slicing
        page_stmt = stmt.offset(skip).limit(pagination.limit)
        data = await session.execute(page_stmt)
        data = data.scalars().all()

        return API_Response( 
            data = [schema(**row.__dict__) for row in data], # unpack dictionary of models` key to initialize schema
            meta = API_Response.MetaData(total=total))
    
    
@router.post('/search', summary='search + pagination for all the polluters')
async def search_polluters(
    pagination: PaginationParams   = Body(description='pagination'),
    filter: Optional[FilterParams] = Body(description='(optional) specified string to search in specified column', default=None)
):
    return await search(pagination, filter, Polluter_OO, Models.Polluter_OO, sessionFactory)


@router.post('/search/polluter-wastes', summary='search + pagination for all the polluters` wastes')
async def search_polluter_wastes(
    pagination: PaginationParams   = Body(description='pagination'),
    filter: Optional[FilterParams] = Body(description='(optional) specified string to search in specified column', default=None)
):
    return await search(pagination, filter, PolluterWaste, Models.PolluterWaste, sessionFactory)